### ISSUE TITLE
Media Queries are not taken into account

### ISSUE THREAD

**Issue by gijsroge** [JanDC/css-from-html-extractor#1]
Lets say you have this as your CSS
```css
.item-in-fold {
   min-width: 450px;
}
.item-outside-fold{
   css-selector: value;
}
@media only screen and (max-width: 1200px) {
   .item-in-fold {
      min-width: 450px;
   }
   .item-outside-fold{
      css-selector: value;
   }
}
```

The CSS selector inside the media query should also be rendered inside the critical css like so:

```html
<style>.item-in-fold{min-width: 450px}@media only screen and (max-width: 1200px) {.item-in-fold {min-width: 450px;}}</style>
```
